## Health Care Spending in OECD Countries
### As the Percentage of GDP Between 1970 and 2017
Data: [OECD](https://stats.oecd.org/index.aspx?DataSetCode=HEALTH_STAT#), Visualization: [Cansin Cagan Acarer](https://cacarer.com/)

I originally created this visualization in JavaScript [link](https://observablehq.com/@cansin/health-care-spending-in-oecd-countries). I recreated it here in Python as a learning exercise.

In [8]:
import pandas as pd
df = pd.read_csv("oecd-data.csv")

I am using the same csv file I created for the other application, so it needs to be retabulated from this:

In [9]:
df.head(10)

         date           name       category  value
0  1970-01-01         Canada         Canada  6.353
1  1970-01-01  United States  United States  6.232
2  1970-01-01        Germany  United States  5.713
3  1970-01-01         Sweden         Sweden  5.506
4  1970-01-01         France         France  5.184
5  1970-01-01    New Zealand    New Zealand  5.073
6  1970-01-01        Finland        Finland  4.986
7  1970-01-01        Ireland        Ireland  4.907
8  1970-01-01    Switzerland    Switzerland  4.901
9  1970-01-01        Austria        Austria  4.838

into this:

In [10]:
dfr = df.pivot_table(index='date', columns='name', values=['date','value'])
dfr

               value                                                        \
name       Australia Austria Belgium  Canada  Chile Czech Republic Denmark
date
1970-01-01     0.000   4.838   3.836   6.353  0.000          0.000   0.000
1971-01-01     4.548   4.770   3.922   6.611  0.000          0.000   7.677
1972-01-01     4.548   4.765   4.076   6.528  0.000          0.000   7.768
1973-01-01     4.512   4.857   4.355   6.207  0.000          0.000   7.585
1974-01-01     5.114   5.086   4.419   6.091  0.000          0.000   8.291
1975-01-01     5.761   6.507   5.518   6.538  0.000          0.000   8.536
1976-01-01     5.778   6.740   5.725   6.574  0.000          0.000   8.441
1977-01-01     6.078   6.681   6.193   6.553  0.000          0.000   8.259
1978-01-01     5.940   6.949   6.382   6.526  0.000          0.000   8.377
1979-01-01     5.830   6.924   6.364   6.414  0.000          0.000   8.474
1980-01-01     5.831   7.022   6.148   6.588  0.000          0.000   8.416
1981-01-01     5.841   6.024   6.561   6.789  0.000          0.000   8.575
1982-01-01     6.107   5.999   6.788   7.522  0.000          0.000   8.624
1983-01-01     6.054   5.832   6.954   7.694  0.000          0.000   8.418
1984-01-01     6.025   5.879   6.797   7.580  0.000          0.000   7.970
1985-01-01     6.077   6.008   6.846   7.588  0.000          0.000   7.947
1986-01-01     6.275   6.115   7.017   7.830  0.000          0.000   7.734
1987-01-01     6.111   6.405   7.123   7.771  0.000          0.000   8.054
1988-01-01     6.066   6.397   7.122   7.769  0.000          0.000   8.191
1989-01-01     6.118   6.540   7.066   7.976  0.000          0.000   8.061
1990-01-01     6.479   7.718   7.109   8.394  0.000          3.736   8.038
1991-01-01     6.776   7.782   7.419   9.081  0.000          3.872   7.940
1992-01-01     6.841   8.077   7.598   9.332  0.000          3.995   7.956
1993-01-01     6.857   8.601   7.722   9.216  0.000          5.351   8.289
1994-01-01     6.889   8.990   7.520   8.862  0.000          5.513   8.077
1995-01-01     6.935   8.924   7.479   8.559  0.000          5.736   7.771
1996-01-01     7.074   8.884   7.754   8.363  0.000          5.620   7.839
1997-01-01     7.088   8.984   7.612   8.345  0.000          5.631   7.750
1998-01-01     7.248   9.150   7.735   8.577  0.000          5.620   7.552
1999-01-01     7.334   9.302   7.900   8.358  0.000          5.796   8.342
2000-01-01     7.617   9.204   7.942   8.276  7.035          5.718   8.104
2001-01-01     7.699   9.269   8.105   8.655  7.151          5.888   8.448
2002-01-01     7.897   9.395   8.263   8.888  7.266          6.199   8.703
2003-01-01     7.912   9.547   9.043   9.043  7.333          6.554   8.904
2004-01-01     8.118   9.709   9.054   9.097  6.901          6.385   9.007
2005-01-01     7.996   9.627   8.966   9.064  6.589          6.381   9.091
2006-01-01     8.000   9.531   8.863   9.207  6.035          6.196   9.169
2007-01-01     8.078   9.532   8.889   9.298  6.175          6.016   9.325
2008-01-01     8.268   9.726   9.272   9.465  6.740          6.360   9.511
2009-01-01     8.577  10.226   9.996  10.574  7.209          7.293  10.674
2010-01-01     8.445  10.221   9.841  10.556  6.775          6.928  10.333
2011-01-01     8.557  10.026  10.004  10.230  6.772          6.977  10.153
2012-01-01     8.689  10.199  10.107  10.240  7.021          7.028  10.241
2013-01-01     8.774  10.286  10.271  10.133  7.359          7.807  10.170
2014-01-01     9.055  10.371  10.341   9.970  7.624          7.653  10.172
2015-01-01     9.330  10.343  10.106  10.377  8.022          7.149  10.274
2016-01-01     9.252  10.438  10.038  10.535  8.189          7.142  10.350
2017-01-01     9.133  10.321  10.020  10.411  8.091          7.079  10.218

                                    ...                                  \
name       Estonia Finland  France  ... Poland Portugal Slovak Republic
date                                ...
1970-01-01   0.000   4.986   5.184  ...  0.000    2.261           0.000
1971-01-01   0.000   5.286   0.000  ...  0.000    2.422           0.000
1972-01-01   0.000   5.381   0.000  ...  0.000    2.988           0.000
1973-01-01   0.000   5.231   0.000  ...  0.000    3.231           0.000
1974-01-01   0.000   5.168   0.000  ...  0.000    3.456           0.000
1975-01-01   0.000   5.650   6.136  ...  0.000    4.731           0.000
1976-01-01   0.000   5.988   0.000  ...  0.000    4.579           0.000
1977-01-01   0.000   6.192   0.000  ...  0.000    4.086           0.000
1978-01-01   0.000   6.131   0.000  ...  0.000    4.214           0.000
1979-01-01   0.000   5.985   0.000  ...  0.000    4.095           0.000
1980-01-01   0.000   5.912   6.737  ...  0.000    4.789           0.000
1981-01-01   0.000   6.036   0.000  ...  0.000    5.024           0.000
1982-01-01   0.000   6.129   0.000  ...  0.000    5.084           0.000
1983-01-01   0.000   6.217   0.000  ...  0.000    4.824           0.000
1984-01-01   0.000   6.261   0.000  ...  0.000    4.950           0.000
1985-01-01   0.000   6.654   7.643  ...  0.000    5.367           0.000
1986-01-01   0.000   6.753   0.000  ...  0.000    5.932           0.000
1987-01-01   0.000   6.893   0.000  ...  0.000    5.768           0.000
1988-01-01   0.000   6.700   0.000  ...  0.000    6.008           0.000
1989-01-01   0.000   6.740   0.000  ...  0.000    5.538           0.000
1990-01-01   0.000   7.248   7.958  ...  4.333    5.516           0.000
1991-01-01   0.000   8.314   8.180  ...  4.795    6.039           0.000
1992-01-01   0.000   8.514   8.403  ...  5.022    6.186           0.000
1993-01-01   0.000   7.829   8.809  ...  5.122    6.452           0.000
1994-01-01   0.000   7.283   8.793  ...  5.004    6.427           0.000
1995-01-01   0.000   7.354   9.830  ...  4.923    7.199           0.000
1996-01-01   0.000   7.476   9.834  ...  5.242    7.452           0.000
1997-01-01   0.000   7.132   9.709  ...  5.107    7.413           5.654
1998-01-01   0.000   6.823   9.610  ...  5.031    7.381           5.551
1999-01-01   5.704   6.798   9.611  ...  5.466    7.620           5.540
2000-01-01   5.165   6.837   9.541  ...  5.298    8.375           5.313
2001-01-01   4.788   6.985   9.665  ...  5.679    8.404           5.340
2002-01-01   4.733   7.359   9.982  ...  6.079    8.558           5.517
2003-01-01   4.885   7.663  10.041  ...  5.962    8.902           5.458
2004-01-01   5.093   7.791  10.124  ...  5.869    9.295           6.480
2005-01-01   4.956   7.998  10.180  ...  5.807    9.433           6.598
2006-01-01   4.918   8.005  10.328  ...  5.801    9.136           6.862
2007-01-01   5.028   7.826  10.263  ...  5.873    9.066           7.190
2008-01-01   5.752   8.084  10.454  ...  6.373    9.353           6.966
2009-01-01   6.543   8.872  11.244  ...  6.587    9.879           7.957
2010-01-01   6.334   8.869  11.179  ...  6.419    9.819           7.801
2011-01-01   5.823   8.949  11.194  ...  6.234    9.531           7.418
2012-01-01   5.827   9.291  11.321  ...  6.201    9.348           7.634
2013-01-01   6.010   9.492  11.442  ...  6.375    9.090           7.528
2014-01-01   6.208   9.480  11.595  ...  6.248    9.022           6.908
2015-01-01   6.482   9.743  11.501  ...  6.343    8.972           6.868
2016-01-01   6.684   9.493  11.539  ...  6.516    9.076           7.125
2017-01-01   6.719   9.220  11.458  ...  6.675    8.985           7.060

                                                                      \
name       Slovenia  Spain  Sweden Switzerland Turkey United Kingdom
date
1970-01-01    0.000  3.145   5.506       4.901  0.000          3.971
1971-01-01    0.000  3.584   5.944       5.120  0.000          4.017
1972-01-01    0.000  3.782   6.046       5.086  0.000          4.088
1973-01-01    0.000  3.699   6.020       5.161  0.000          4.019
1974-01-01    0.000  4.028   6.260       5.512  0.000          4.647
1975-01-01    0.000  4.192   6.545       6.281  2.156          4.933
1976-01-01    0.000  4.668   6.831       6.502  1.695          4.949
1977-01-01    0.000  4.916   7.588       6.497  1.988          4.846
1978-01-01    0.000  4.954   7.636       6.507  2.226          4.798
1979-01-01    0.000  4.902   7.526       6.598  2.293          4.740
1980-01-01    0.000  4.967   7.836       6.631  2.361          5.063
1981-01-01    0.000  5.104   7.939       6.691  2.574          5.285
1982-01-01    0.000  5.196   8.026       6.828  2.146          5.123
1983-01-01    0.000  5.348   7.937       7.192  2.194          5.321
1984-01-01    0.000  5.160   7.745       6.952  2.114          5.237
1985-01-01    0.000  5.044   7.352       7.510  1.490          5.140
1986-01-01    0.000  5.005   7.121       7.676  1.835          5.125
1987-01-01    0.000  5.074   7.200       7.859  1.896          5.178
1988-01-01    0.000  5.643   7.116       7.903  2.074          5.089
1989-01-01    0.000  5.767   7.175       7.909  2.275          5.037
1990-01-01    0.000  6.101   7.256       7.852  2.451          5.090
1991-01-01    0.000  6.288   7.244       8.479  2.786          5.486
1992-01-01    0.000  6.663   7.528       8.858  2.747          5.935
1993-01-01    0.000  6.967   7.772       8.962  2.695          6.003
1994-01-01    0.000  6.893   7.377       9.090  2.624          6.078
1995-01-01    0.000  7.048   7.292       9.321  2.448          5.600
1996-01-01    0.000  7.069   7.496       9.700  2.834          5.589
1997-01-01    0.000  6.953   7.318       9.720  3.060          5.469
1998-01-01    0.000  6.917   7.402       9.831  3.509          5.614
1999-01-01    0.000  6.923   7.415       9.961  4.465          5.854
2000-01-01    7.784  6.816   7.412       9.844  4.622          5.972
2001-01-01    7.876  6.783   8.034      10.231  4.924          6.329
2002-01-01    7.996  6.803   8.362      10.641  5.101          6.587
2003-01-01    8.082  7.530   8.464      10.936  5.059          6.851
2004-01-01    7.927  7.619   8.261      11.004  4.959          7.051
2005-01-01    7.965  7.676   8.277      10.822  4.942          7.187
2006-01-01    7.802  7.755   8.161      10.214  5.188          7.327
2007-01-01    7.494  7.837   8.074      10.016  5.281          7.432
2008-01-01    7.849  8.289   8.313      10.151  5.259          7.681
2009-01-01    8.562  8.989   8.944      10.809  5.534          8.527
2010-01-01    8.591  9.022   8.486      10.699  5.054          8.474
2011-01-01    8.574  9.091  10.679      10.769  4.688          8.422
2012-01-01    8.758  9.076  10.938      11.058  4.478          8.339
2013-01-01    8.792  9.025  11.101      11.314  4.404          9.772
2014-01-01    8.506  9.024  11.141      11.494  4.347          9.724
2015-01-01    8.502  9.120  11.008      11.894  4.139          9.793
2016-01-01    8.468  8.970  10.935      12.248  4.314          9.762
2017-01-01    7.972  8.841  10.916      12.259  4.227          9.645


name       United States
date
1970-01-01         6.232
1971-01-01         6.366
1972-01-01         6.499
1973-01-01         6.517
1974-01-01         6.836
1975-01-01         7.171
1976-01-01         7.419
1977-01-01         7.668
1978-01-01         7.640
1979-01-01         7.772
1980-01-01         8.226
1981-01-01         8.515
1982-01-01         9.209
1983-01-01         9.330
1984-01-01         9.284
1985-01-01         9.498
1986-01-01         9.667
1987-01-01         9.903
1988-01-01        10.290
1989-01-01        10.645
1990-01-01        11.273
1991-01-01        11.948
1992-01-01        12.215
1993-01-01        12.469
1994-01-01        12.392
1995-01-01        12.502
1996-01-01        12.464
1997-01-01        12.369
1998-01-01        12.392
1999-01-01        12.390
2000-01-01        12.502
2001-01-01        13.169
2002-01-01        13.954
2003-01-01        14.455
2004-01-01        14.537
2005-01-01        14.541
2006-01-01        14.658
2007-01-01        14.898
2008-01-01        15.294
2009-01-01        16.343
2010-01-01        16.413
2011-01-01        16.367
2012-01-01        16.366
2013-01-01        16.331
2014-01-01        16.505
2015-01-01        16.816
2016-01-01        17.073
2017-01-01        17.150

[48 rows x 36 columns]